/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.lexer.Lexer;
import com.mycompany.lexer.Token;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Eleazr
 */
public class VentanaAnalizador extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAnalizador
     */
    public VentanaAnalizador() {
        initComponents();
        String code ="";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        paraImagen = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 306, 378));

        javax.swing.GroupLayout paraImagenLayout = new javax.swing.GroupLayout(paraImagen);
        paraImagen.setLayout(paraImagenLayout);
        paraImagenLayout.setHorizontalGroup(
            paraImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paraImagenLayout.setVerticalGroup(
            paraImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        getContentPane().add(paraImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 6, 379, -1));

        jButton1.setText("REALIZAR ANÁLISIS LÉXICO\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 396, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String code = jTextArea1.getText(); 
        // Crear instancia del analizador léxico
        Lexer lexer = new Lexer(code);

        // Obtener la lista de tokens
        List<Token> tokens = lexer.tokenize();
        paintTextInPanel(code);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void paintTextInPanel(String text) {
    paraImagen.removeAll(); // Limpiar el panel antes de pintar
    paraImagen.repaint();

    // Crear un componente que dibuja el texto
    JPanel textPanel = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.setColor(Color.BLACK); // Color del texto
            g.drawString(text, 10, 20); // Dibuja el texto en el panel
        }
    };

    // Ajustar el tamaño del panel de texto para que coincida con el tamaño del JPanel
    textPanel.setPreferredSize(new Dimension(379, 378));

    paraImagen.add(textPanel);
    paraImagen.revalidate(); // Revalidar para actualizar la vista
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel paraImagen;
    // End of variables declaration//GEN-END:variables
}
