/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.lexer;

/**
 *
 * @author 3198935960914 - Eleazar Colop
 */
public enum TokenType {
    IDENTIFICADOR,
    
    OPERADOR_ARITMETICO_SUMA,
    OPERADOR_ARITMETICO_RESTA,
    OPERADOR_ARITMETICO_EXPONENTE,
    OPERADOR_ARITMETICO_DIVISION,
    OPERADOR_ARITMETICO_MODULO,
    OPERADOR_ARITMETICO_MULTIPLICACION,
    
    OPERADOR_RELACIONAL_IGUAL,
    OPERADOR_RELACIONAL_DIFERENTE,
    OPERADOR_RELACIONAL_MAYOR,
    OPERADOR_RELACIONAL_MENOR,
    OPERADOR_RELACIONAL_MAYOR_IGUAL,
    OPERADOR_RELACIONAL_MENOR_IGUAL,
    
    OPERADOR_LOGICO_Y,
    OPERADOR_LOGICO_O,
    OPERADOR_LOGICO_NEGACION,
    
    OPERADOR_ASIGNACION,
    OPERADOR_ASIGNACION_COMPUESTA,
    
    PALABRA_RESERVADA_MODULE,
    PALABRA_RESERVADA_END,
    PALABRA_RESERVADA_SUB,
    PALABRA_RESERVADA_MAIN,
    PALABRA_RESERVADA_DIM,
    PALABRA_RESERVADA_AS,
    PALABRA_RESERVADA_INTEGER,
    PALABRA_RESERVADA_STRING,
    PALABRA_RESERVADA_BOOLEAN,
    PALABRA_RESERVADA_DOUBLE,
    PALABRA_RESERVADA_CHAR,
    PALABRA_RESERVADA_CONSOLE_WRITE_LINE,
    PALABRA_RESERVADA_CONSOLE_READ_LINE,
    PALABRA_RESERVADA_IF,
    PALABRA_RESERVADA_ELSE_IF,
    PALABRA_RESERVADA_ELSE,
    PALABRA_RESERVADA_THEN,
    PALABRA_RESERVADA_WHILE,
    PALABRA_RESERVADA_DO,
    PALABRA_RESERVADA_LOOP,
    PALABRA_RESERVADA_FOR,
    PALABRA_RESERVADA_TO,
    PALABRA_RESERVADA_NEXT,
    PALABRA_RESERVADA_FUNCTION,
    PALABRA_RESERVADA_RETURN,
    PALABRA_RESERVADA_CONST,
    
    TIPO_DATO_ENTERO,
    TIPO_DATO_DECIMAL,
    TIPO_DATO_CADENA,
    TIPO_DATO_BOOLEANO,
    TIPO_DATO_CARACTER,
    
    CUADRO_COLOR,
    
    COMENTARIO,
    PARANTESIS,
    LLAVES,
    CORCHETES,
    COMA,
    PUNTO,
    DESCONOCIDO
}

